import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head>

      <main className={styles.main}>
        <div>Hi, my name is</div>
        <div>Guthrie Albertson</div>
        <div>I'm a software developer and college senior from Philadelphia, PA</div>
      </main>
    </>
  );
}
