import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <div className={styles.lineone}>Hi, my name is</div>
        <div className={styles.linetwo}>Guthrie Albertson.</div>
        <div className={styles.linethree}>
          I'm a software developer and senior at Temple University from
          Philadelphia, PA
        </div>
      </main>
    </div>
  );
}
